### ISSUE TITLE
CoreDNS Plugin, caddy.Instance.Restart() leads to panic

### ISSUE THREAD

**Issue by mariuskimmina** [miekg/coredns#5490]
I am currently trying to build a plugin that solves #3460 and let CoreDNS handle it's own certificates automatically with the ACME protocol.

At the moment I am facing an Issue regarding the certificate renewal. When a certificate is being renewed it seems unavoidable to restart CoreDNS to use this new certificate, updating the `dnsserver.config` seems to have no effect when CoreDNS is already running (please correct me if I am wrong here).
I looked at the `reload` plugin, which seems to be doing such a restart and tried to copy it's approach into my plugin.

```
type renewCert struct {
        quit chan bool
}

func hook(event caddy.EventName, info interface{}) error {
        if event != caddy.InstanceStartupEvent {
                return nil
        }

        instance := info.(*caddy.Instance)


        go func() {
                tick := time.NewTicker(40 * time.Second)

                for {
                        select {
                        case <-tick.C:
                                corefile, err := caddy.LoadCaddyfile(instance.Caddyfile().ServerType())
                                if err != nil {
                                        continue
                                }
                                _, err = instance.Restart(corefile)
                                if err != nil {
                                       fmt.Printf("Error during Restart: %v, \n", err)
                                }
                                return
                        case <-r.quit:
                                return
                        }
                }
        }()
        return nil
}
```
I'm also initiating this hook the same way the `reload` plugin does
```
            once.Do(func() {
                caddy.RegisterEventHook("updateCert", hook)
            })
            shutOnce.Do(func() {
                c.OnFinalShutdown(func() error {
                    r.quit <- true
                    return nil
                })
            })
```

The restart happens as expected, but then CoreDNS panics and I can't seem to figure out why

```
2022/07/06 12:08:55 [INFO] Reloading complete
panic: sync: negative WaitGroup counter

goroutine 395 [running]:
sync.(*WaitGroup).Add(0xc000c1c0c0?, 0x0?)
        /usr/local/go/src/sync/waitgroup.go:80 +0xda
sync.(*WaitGroup).Done(...)
        /usr/local/go/src/sync/waitgroup.go:105
github.com/coredns/coredns/core/dnsserver.(*Server).Stop.func1()
        /home/marius/go/pkg/mod/github.com/coredns/coredns@v1.9.3/core/dnsserver/server.go:174 +0x38
created by github.com/coredns/coredns/core/dnsserver.(*Server).Stop
        /home/marius/go/pkg/mod/github.com/coredns/coredns@v1.9.3/core/dnsserver/server.go:173 +0x9d
```

I would be thankful for any help in figuring out why this panic happens.

**Comment by mariuskimmina** [comment]
After a bit more debugging, it appears that this panic wasn't (directly) related to the reload but rather it occured further down my test case. Correlation does not imply causation. I stil haven't fully figured out what's going wrong but I am closing this issue for now.
If anyone is interested the plugin I am working on can be found here: https://github.com/mariuskimmina/coredns-tlsplus (work in progress)
