### ISSUE TITLE
coredns-node panics due to dereferencing a nil pointer

### ISSUE THREAD

**Issue by gman0** [miekg/coredns#5848]
**What happened**:

In one of our Kubernetes clusters we've seen coredns-node pod panic due to dereferencing a nil pointer.

```
(a lot of "connect: no route to host" errors)
...
E1230 11:19:22.740170       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Namespace: Get https://10.254.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.254.0.1:443: connect: no route to host
I1230 11:19:23.860800       1 trace.go:82] Trace[1423638522]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2022-12-30 11:19:11.732391632 +0000 UTC m=+21957240.399736536) (total time: 12.128367971s):
Trace[1423638522]: [12.123284493s] [12.123284493s] Objects listed
E1230 11:19:23.868186       1 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
E1230 11:19:23.868186       1 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 84 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x184cd40, 0x2aa6a40)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/runtime/runtime.go:51 +0x82
panic(0x184cd40, 0x2aa6a40)
	/tmp/tmp.7IFQOqEt6M/go/src/runtime/panic.go:679 +0x1b2
github.com/coredns/coredns/plugin/kubernetes/object.(*Endpoints).GetNamespace(0x0, 0x0, 0x7fe40ac6c748)
	/tmp/tmp.7IFQOqEt6M/g/src/github.com/coredns/coredns/plugin/kubernetes/object/endpoint.go:146 +0x5
k8s.io/client-go/tools/cache.MetaNamespaceKeyFunc(0x1a50a80, 0x0, 0x1, 0xc000f7b590, 0x1, 0x1)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/store.go:84 +0x10e
k8s.io/client-go/tools/cache.DeletionHandlingMetaNamespaceKeyFunc(0x1a50a80, 0x0, 0x1, 0x1, 0x203000, 0x203000)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:261 +0x6a
k8s.io/client-go/tools/cache.(*cache).Delete(0xc000323f60, 0x1a50a80, 0x0, 0x0, 0x18)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/store.go:144 +0x42
github.com/coredns/coredns/plugin/kubernetes.newdnsController.func1.1(0x186e2c0, 0xc0019d09a0, 0x1, 0xc0019d09a0)
	/tmp/tmp.7IFQOqEt6M/g/src/github.com/coredns/coredns/plugin/kubernetes/controller.go:167 +0x5df
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0000a9130, 0xc0000e82d0, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/delta_fifo.go:436 +0x230
goroutine 84 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x184cd40, 0x2aa6a40)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/runtime/runtime.go:51 +0x82
panic(0x184cd40, 0x2aa6a40)
	/tmp/tmp.7IFQOqEt6M/go/src/runtime/panic.go:679 +0x1b2
github.com/coredns/coredns/plugin/kubernetes/object.(*Endpoints).GetNamespace(0x0, 0x0, 0x7fe40ac6c748)
	/tmp/tmp.7IFQOqEt6M/g/src/github.com/coredns/coredns/plugin/kubernetes/object/endpoint.go:146 +0x5
k8s.io/client-go/tools/cache.MetaNamespaceKeyFunc(0x1a50a80, 0x0, 0x1, 0xc000f7b590, 0x1, 0x1)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/store.go:84 +0x10e
k8s.io/client-go/tools/cache.DeletionHandlingMetaNamespaceKeyFunc(0x1a50a80, 0x0, 0x1, 0x1, 0x203000, 0x203000)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:261 +0x6a
k8s.io/client-go/tools/cache.(*cache).Delete(0xc000323f60, 0x1a50a80, 0x0, 0x0, 0x18)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/store.go:144 +0x42
github.com/coredns/coredns/plugin/kubernetes.newdnsController.func1.1(0x186e2c0, 0xc0019d09a0, 0x1, 0xc0019d09a0)
	/tmp/tmp.7IFQOqEt6M/g/src/github.com/coredns/coredns/plugin/kubernetes/controller.go:167 +0x5df
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0000a9130, 0xc0000e82d0, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/delta_fifo.go:436 +0x230
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc000150b80)
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc000150b80)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:150 +0x40
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000278fb0)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000278fb0, 0x3b9aca00, 0x0, 0xc0000e5501, 0xc0001b0300)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*controller).Run(0xc000150b80, 0xc0001b0300)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:124 +0x2fd
created by github.com/coredns/coredns/plugin/kubernetes.(*dnsControl).Run
	/tmp/tmp.7IFQOqEt6M/g/src/github.com/coredns/coredns/plugin/kubernetes/controller.go:304 +0x12b
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:150 +0x40
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000278fb0)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000278fb0, 0x3b9aca00, 0x0, 0xc0000e5501, 0xc0001b0300)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*controller).Run(0xc000150b80, 0xc0001b0300)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:124 +0x2fd
created by github.com/coredns/coredns/plugin/kubernetes.(*dnsControl).Run
	/tmp/tmp.7IFQOqEt6M/g/src/github.com/coredns/coredns/plugin/kubernetes/controller.go:304 +0x12b
E1230 11:19:23.868186       1 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 84 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x184cd40, 0x2aa6a40)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/runtime/runtime.go:51 +0x82
panic(0x184cd40, 0x2aa6a40)
	/tmp/tmp.7IFQOqEt6M/go/src/runtime/panic.go:679 +0x1b2
github.com/coredns/coredns/plugin/kubernetes/object.(*Endpoints).GetNamespace(0x0, 0x0, 0x7fe40ac6c748)
	/tmp/tmp.7IFQOqEt6M/g/src/github.com/coredns/coredns/plugin/kubernetes/object/endpoint.go:146 +0x5
k8s.io/client-go/tools/cache.MetaNamespaceKeyFunc(0x1a50a80, 0x0, 0x1, 0xc000f7b590, 0x1, 0x1)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/store.go:84 +0x10e
k8s.io/client-go/tools/cache.DeletionHandlingMetaNamespaceKeyFunc(0x1a50a80, 0x0, 0x1, 0x1, 0x203000, 0x203000)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:261 +0x6a
k8s.io/client-go/tools/cache.(*cache).Delete(0xc000323f60, 0x1a50a80, 0x0, 0x0, 0x18)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/store.go:144 +0x42
github.com/coredns/coredns/plugin/kubernetes.newdnsController.func1.1(0x186e2c0, 0xc0019d09a0, 0x1, 0xc0019d09a0)
	/tmp/tmp.7IFQOqEt6M/g/src/github.com/coredns/coredns/plugin/kubernetes/controller.go:167 +0x5df
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0000a9130, 0xc0000e82d0, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/delta_fifo.go:436 +0x230
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc000150b80)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:150 +0x40
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000278fb0)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000278fb0, 0x3b9aca00, 0x0, 0xc0000e5501, 0xc0001b0300)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*controller).Run(0xc000150b80, 0xc0001b0300)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:124 +0x2fd
created by github.com/coredns/coredns/plugin/kubernetes.(*dnsControl).Run
	/tmp/tmp.7IFQOqEt6M/g/src/github.com/coredns/coredns/plugin/kubernetes/controller.go:304 +0x12b
E1230 11:19:23.868186       1 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 84 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x184cd40, 0x2aa6a40)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/runtime/runtime.go:51 +0x82
panic(0x184cd40, 0x2aa6a40)
	/tmp/tmp.7IFQOqEt6M/go/src/runtime/panic.go:679 +0x1b2
github.com/coredns/coredns/plugin/kubernetes/object.(*Endpoints).GetNamespace(0x0, 0x0, 0x7fe40ac6c748)
	/tmp/tmp.7IFQOqEt6M/g/src/github.com/coredns/coredns/plugin/kubernetes/object/endpoint.go:146 +0x5
k8s.io/client-go/tools/cache.MetaNamespaceKeyFunc(0x1a50a80, 0x0, 0x1, 0xc000f7b590, 0x1, 0x1)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/store.go:84 +0x10e
k8s.io/client-go/tools/cache.DeletionHandlingMetaNamespaceKeyFunc(0x1a50a80, 0x0, 0x1, 0x1, 0x203000, 0x203000)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:261 +0x6a
k8s.io/client-go/tools/cache.(*cache).Delete(0xc000323f60, 0x1a50a80, 0x0, 0x0, 0x18)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/store.go:144 +0x42
github.com/coredns/coredns/plugin/kubernetes.newdnsController.func1.1(0x186e2c0, 0xc0019d09a0, 0x1, 0xc0019d09a0)
	/tmp/tmp.7IFQOqEt6M/g/src/github.com/coredns/coredns/plugin/kubernetes/controller.go:167 +0x5df
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0000a9130, 0xc0000e82d0, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/delta_fifo.go:436 +0x230
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc000150b80)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:150 +0x40
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000278fb0)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000278fb0, 0x3b9aca00, 0x0, 0xc0000e5501, 0xc0001b0300)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/apimachinery@v0.0.0-20190612205821-1799e75a0719/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*controller).Run(0xc000150b80, 0xc0001b0300)
	/tmp/tmp.7IFQOqEt6M/g/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/controller.go:124 +0x2fd
created by github.com/coredns/coredns/plugin/kubernetes.(*dnsControl).Run
	/tmp/tmp.7IFQOqEt6M/g/src/github.com/coredns/coredns/plugin/kubernetes/controller.go:304 +0x12b
I1230 11:19:23.966037       1 trace.go:82] Trace[1907438527]: "Reflector pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98 ListAndWatch" (started: 2022-12-30 11:19:11.733461681 +0000 UTC m=+21957240.400806588) (total time: 12.232524704s):
Trace[1907438527]: [12.204407805s] [12.204407805s] Objects listed
```

I'm not sure it's related, but we've seen occasional `connect: no route to host` which then makes coredns stuck, that in turn makes the application pods fail. This only seems to be solved by restarting the affected coredns-node pod (and possibly the apps too). We're still trying to debug why this happens. We're using calico v3.13.2.

**How to reproduce it (as minimally and precisely as possible)**:

I cannot say for sure unfortunately, but the stack trace might pinpoint the reason of the panic closer.

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 1.8.6
- Corefile:
  ```
      .:53 {
        errors
        log stdout
        health
        kubernetes cluster.local 10.254.0.0/16 10.100.0.0/16 {
           pods verified
           fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 900
        loop
        reload
        loadbalance
    }
  ```
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`): Fedora CoreOS 34.20210529.3.0
- Others: Kubernetes version `Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by chrisohaver** [comment]
Can you doublecheck the version of CoreDNS being used please?  The stacktrace shows a very old version of the k8s api client, which suggests a version of CoreDNS from around 2019.

This looks a lot like an error circa CoreDNS 1.6.x, that was fixed in 1.7.0. https://github.com/coredns/coredns/issues/4022

**Comment by gman0** [comment]
```
$ kubectl -n kube-system logs coredns-5b6d5d5566-5msgm
.:53
[INFO] plugin/reload: Running configuration MD5 = 1f1c62efb4e37e8124304c13b2483b1e
CoreDNS-1.8.6
linux/amd64, go1.17.1, 13a9191
```

**Comment by chrisohaver** [comment]
Hmm. Our release of 1.8.6 used client-go v0.22.2.

**Comment by chrisohaver** [comment]
It looks like your stack trace is from an instance of coredns v1.6.6 ...

The version of client-go in the trace (`pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab`), matches the version used in coredns v1.6.6: https://github.com/coredns/coredns/blob/6a7a75e0cc14159177e604d0157836cc32add343/go.mod#L49

Also the line numbers of coredns's files in the stack trace actually line up with coredns v1.6.6, not v1.8.6: 

e.g. for the stack trace entry: `... plugin/kubernetes/object.(*Endpoints).GetNamespace ... plugin/kubernetes/object/endpoint.go:146 +0x5`

1.6.6 has GetNamespace on line 146 as expected : https://github.com/coredns/coredns/blob/6a7a75e0cc14159177e604d0157836cc32add343/plugin/kubernetes/object/endpoint.go#L146

1.8.6 does not: https://github.com/coredns/coredns/blob/13a9191efb0574cc92ed5ffd55a1f144b840d668/plugin/kubernetes/object/endpoint.go#L146
