### ISSUE TITLE
CoreDNS(local dns)  is crashed  due to high concurrency stress traffic

### ISSUE THREAD

**Issue by zengyuxing007** [miekg/coredns#6573]
**What happened**:

CoreDNS is crashed due to high concurrency stress traffic.

```
panic: too many concurrent operations on a single file or socket (max 1048575)
```
The plugin `loop` is configured , and there is no loop-type dns request query.  

It just seems like a lot of dns traffic.  there may be more out-of-cluster domain name queries. (Ref Issue:  https://github.com/istio/istio/issues/50119)

The More Logs :

```shell
[ERROR] Recovered from panic in server: "dns://:53" too many concurrent operations on a single file or socket (max 1048575)
[ERROR] Recovered from panic in server: "dns://:53" too many concurrent operations on a single file or socket (max 1048575)
[ERROR] Recovered from panic in server: "dns://:53" too many concurrent operations on a single file or socket (max 1048575)
[ERROR] Recovered from panic in server: "dns://:53" too many concurrent operations on a single file or socket (max 1048575)
panic: too many concurrent operations on a single file or socket (max 1048575) [recovered]
	panic: too many concurrent operations on a single file or socket (max 1048575)

goroutine 3314264 [running]:
internal/poll.(*fdMutex).rwlock(0xc0007bc900, 0xc0?)
	/usr/local/go/src/internal/poll/fd_mutex.go:147 +0x11b
internal/poll.(*FD).writeLock(...)
	/usr/local/go/src/internal/poll/fd_mutex.go:239
internal/poll.(*FD).WriteMsg(0xc0007bc900, {0xc2e5aa2ba0, 0x22, 0x23}, {0xc2e5adc0c0, 0x20, 0x20}, {0x2365f60, 0xc2e549f940})
	/usr/local/go/src/internal/poll/fd_unix.go:518 +0xa5
net.(*netFD).writeMsg(0xc0007bc900, {0xc2e5aa2ba0?, 0x20?, 0x24?}, {0xc2e5adc0c0?, 0x20?, 0xc2e5adc0d0?}, {0x2365f60?, 0xc2e549f940?})
	/usr/local/go/src/net/fd_posix.go:120 +0x45
net.(*UDPConn).writeMsg(0xc00000e508, {0xc2e5aa2ba0, 0x22, 0x23}, {0xc2e5adc0c0, 0x20, 0x20}, 0x6fe1b5?)
	/usr/local/go/src/net/udpsock_posix.go:176 +0xd6
net.(*UDPConn).WriteMsgUDP(0xc00000e508, {0xc2e5aa2ba0?, 0x0?, 0xc2e5af8601?}, {0xc2e5adc0c0?, 0x0?, 0x0?}, 0xc2e6614900)
	/usr/local/go/src/net/udpsock.go:258 +0x47
github.com/miekg/dns.WriteToSessionUDP(0x6c6c33?, {0xc2e5aa2ba0, 0x22, 0x23}, 0xc2e4e13d20)
	/build/vendor/github.com/miekg/dns/udp.go:52 +0x71
github.com/miekg/dns.(*response).Write(0xc2e5af86e0?, {0xc2e5aa2ba0?, 0x72ae8d?, 0xc2e5af8718?})
	/build/vendor/github.com/miekg/dns/server.go:756 +0x4b
github.com/miekg/dns.(*response).WriteMsg(0xc2e54e1880, 0xc2e5ad10e0?)
	/build/vendor/github.com/miekg/dns/server.go:743 +0x8e
github.com/coredns/coredns/request.(*ScrubWriter).WriteMsg(0xc2e5ae0150, 0x2382ed8?)
	/build/request/writer.go:20 +0x98
github.com/coredns/coredns/core/dnsserver.errorAndMetricsFunc({0xc000798815, 0x9}, {0x2382ed8, 0xc2e5ae0150}, 0xc2e5ad0f30, 0x2)
	/build/core/dnsserver/server.go:340 +0x268
github.com/coredns/coredns/core/dnsserver.(*Server).ServeDNS.func1()
	/build/core/dnsserver/server.go:225 +0x1ef
panic({0x1b72d60, 0x235f8e0})
	/usr/local/go/src/runtime/panic.go:838 +0x207
internal/poll.(*fdMutex).rwlock(0xc0007bc900, 0xc0?)
	/usr/local/go/src/internal/poll/fd_mutex.go:147 +0x11b
internal/poll.(*FD).writeLock(...)
	/usr/local/go/src/internal/poll/fd_mutex.go:239
internal/poll.(*FD).WriteMsg(0xc0007bc900, {0xc2e5ad20f0, 0x42, 0x43}, {0xc2e5adc0a0, 0x20, 0x20}, {0x2365f60, 0xc2e549f900})
	/usr/local/go/src/internal/poll/fd_unix.go:518 +0xa5
net.(*netFD).writeMsg(0xc0007bc900, {0xc2e5ad20f0?, 0x20?, 0x24?}, {0xc2e5adc0a0?, 0x20?, 0xc2e5adc0b0?}, {0x2365f60?, 0xc2e549f900?})
	/usr/local/go/src/net/fd_posix.go:120 +0x45
net.(*UDPConn).writeMsg(0xc00000e508, {0xc2e5ad20f0, 0x42, 0x43}, {0xc2e5adc0a0, 0x20, 0x20}, 0x6fe1b5?)
	/usr/local/go/src/net/udpsock_posix.go:176 +0xd6
net.(*UDPConn).WriteMsgUDP(0xc00000e508, {0xc2e5ad20f0?, 0x0?, 0x1?}, {0xc2e5adc0a0?, 0x0?, 0x0?}, 0xc2e6614900)
	/usr/local/go/src/net/udpsock.go:258 +0x47
github.com/miekg/dns.WriteToSessionUDP(0x6c6c33?, {0xc2e5ad20f0, 0x42, 0x43}, 0xc2e4e13d20)
	/build/vendor/github.com/miekg/dns/udp.go:52 +0x71
github.com/miekg/dns.(*response).Write(0x22?, {0xc2e5ad20f0?, 0x72ae8d?, 0xc2e5af0e68?})
	/build/vendor/github.com/miekg/dns/server.go:756 +0x4b
github.com/miekg/dns.(*response).WriteMsg(0xc2e54e1880, 0xc2e5ad1050?)
	/build/vendor/github.com/miekg/dns/server.go:743 +0x8e
github.com/coredns/coredns/request.(*ScrubWriter).WriteMsg(0xc2e5ae0150, 0x32263e0?)
	/build/request/writer.go:20 +0x98
github.com/coredns/coredns/plugin/pkg/dnstest.(*Recorder).WriteMsg(0xc2e5ac53c0, 0xc2e5ad1050)
	/build/plugin/pkg/dnstest/recorder.go:44 +0x68
github.com/coredns/coredns/plugin/metrics.(*Recorder).WriteMsg(0xc2e5ac5400, 0xc2e5acc310?)
	/build/plugin/metrics/recorder.go:27 +0xb3
github.com/coredns/coredns/plugin/pkg/dnstest.(*Recorder).WriteMsg(0xc2e5ac5440, 0xc2e5ad1050)
	/build/plugin/pkg/dnstest/recorder.go:44 +0x68
github.com/coredns/coredns/plugin/loadbalance.(*RoundRobinResponseWriter).WriteMsg(0xc2e5acc2f0, 0xc2e5ad1050)
	/build/plugin/loadbalance/loadbalance.go:25 +0x13a
github.com/coredns/coredns/plugin/cache.(*Cache).ServeDNS(0xc0004c8630, {0x237dea0?, 0xc2e5ac6ae0}, {0x2382cc8, 0xc2e5acc2f0}, 0x0?)
	/build/plugin/cache/handler.go:66 +0x99e
github.com/coredns/coredns/plugin.NextOrFailure({0x1f3ba10?, 0x4179db?}, {0x2369620, 0xc0004c8630}, {0x237dea0, 0xc2e5ac6ae0}, {0x2382cc8, 0xc2e5acc2f0}, 0xc1fea3e3f8?)
	/build/plugin/plugin.go:80 +0x26a
github.com/coredns/coredns/plugin/loadbalance.RoundRobin.ServeDNS({{0x2369620?, 0xc0004c8630?}}, {0x237dea0, 0xc2e5ac6ae0}, {0x2382dd0?, 0xc2e5ac5440}, 0x9?)
	/build/plugin/loadbalance/handler.go:20 +0xcf
github.com/coredns/coredns/plugin.NextOrFailure({0x1f30f87?, 0x1?}, {0x236f2a0, 0xc000794600}, {0x237dea0, 0xc2e5ac6ae0}, {0x2382dd0, 0xc2e5ac5440}, 0x32aa701?)
	/build/plugin/plugin.go:80 +0x26a
github.com/coredns/coredns/plugin/log.Logger.ServeDNS({{0x236f2a0, 0xc000794600}, {0xc0003d9020, 0x1, 0x1}, {}}, {0x237dea0, 0xc2e5ac6ae0}, {0x2382d20?, 0xc2e5ac5400?}, ...)
	/build/plugin/log/log.go:36 +0x346
github.com/coredns/coredns/plugin.NextOrFailure({0x1f33b05?, 0xc1fea3eda8?}, {0x236f2f0, 0xc0007abaa0}, {0x237dea0, 0xc2e5ac6ae0}, {0x2382d20, 0xc2e5ac5400}, 0x0?)
	/build/plugin/plugin.go:80 +0x26a
github.com/coredns/coredns/plugin/errors.(*errorHandler).ServeDNS(0xc0003d8fc0, {0x237dea0?, 0xc2e5ac6ae0?}, {0x2382d20, 0xc2e5ac5400}, 0xc2e5ad0f30)
	/build/plugin/errors/errors.go:84 +0x87
github.com/coredns/coredns/plugin.NextOrFailure({0x1f3a39b?, 0x1?}, {0x23696c0, 0xc0003d8fc0}, {0x237dea0, 0xc2e5ac6ae0}, {0x2382d20, 0xc2e5ac5400}, 0x0?)
	/build/plugin/plugin.go:80 +0x26a
github.com/coredns/coredns/plugin/metrics.(*Metrics).ServeDNS(0xc0003b65a0, {0x237dea0, 0xc2e5ac6ae0}, {0x2382ed8?, 0xc2e5ae0150}, 0xc2e5ad0f30)
	/build/plugin/metrics/handler.go:27 +0x255
github.com/coredns/coredns/core/dnsserver.(*Server).ServeDNS(0xc000140060, {0x237dea0, 0xc2e5ac6ae0}, {0x2382ed8, 0xc2e5ae0150}, 0xc2e5ad0f30)
	/build/core/dnsserver/server.go:287 +0x64d
github.com/coredns/coredns/core/dnsserver.(*Server).ServePacket.func1({0x23849a8, 0xc2e54e1880}, 0xc2e5ae0138?)
	/build/core/dnsserver/server.go:131 +0x9b
github.com/miekg/dns.HandlerFunc.ServeDNS(0xc192fa0a00?, {0x23849a8?, 0xc2e54e1880?}, 0xc2e5ad0f30?)
	/build/vendor/github.com/miekg/dns/server.go:37 +0x2f
github.com/miekg/dns.(*Server).serveDNS(0xc000981b00, {0xc192fa0a00, 0x22, 0x200}, 0xc2e54e1880)
	/build/vendor/github.com/miekg/dns/server.go:659 +0x451
github.com/miekg/dns.(*Server).serveUDPPacket(0xc000981b00, 0xc01c6d72e0?, {0xc192fa0a00, 0x22, 0x200}, {0x2382538?, 0xc00000e508}, 0xc2e4e13d20, {0x0, 0x0})
	/build/vendor/github.com/miekg/dns/server.go:603 +0x1dc
created by github.com/miekg/dns.(*Server).serveUDP
	/build/vendor/github.com/miekg/dns/server.go:533 +0x485
panic: too many concurrent operations on a single file or socket (max 1048575) [recovered]
	panic: too many concurrent operations on a single file or socket (max 1048575)
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS:
  v1.7
- Corefile:
```shell
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        cache {
          success 9984 30
          denial 9984 5
        }

        reload
        loop
        bind 169.254.20.10
        forward . 172.16.0.10 {
          force_tcp
        }
        prometheus :9253
        health 169.254.20.10:8081
    }
kind: ConfigMap
```
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
- Others:

Node Local DNS (using CoreDNS core)

**Comment by zengyuxing007** [comment]
`1048575`  Looks like 200000 concurrency + 5s timeout to upstream DNS Server  may trigger ??

**Comment by zengyuxing007** [comment]
https://github.com/coredns/coredns/blob/master/plugin/forward/setup.go#L279

Should we set a default value for the max_concurrent parameter even when it's not be configured?  so we can avoid triggering this panic in Golang .

**Comment by chrisohaver** [comment]
> the version of CoreDNS: v1.7

Can you test on a more up to date version?
1.7 is very old. 

> https://github.com/coredns/coredns/blob/master/plugin/forward/setup.go#L279
> 
> Should we set a default value for the max_concurrent parameter even when it's not be configured? so we can avoid triggering this panic in Golang .

I wouldn’t think so. It appears the issue is related to accepting concurrent incoming connections to the server, not when forward makes connections to upstream servers.

**Comment by chrisohaver** [comment]
> I wouldn’t think so. It appears the issue is related to accepting concurrent incoming connections to the server, not when forward makes connections to upstream servers.

More precisely, when writing responses to those incoming requests.  IIUC, the limit can be reached regardless of whether the forward plugin is in use, so while setting max concurrent in forward might help indirectly, it’s not a good over all solution.

**Comment by zengyuxing007** [comment]
@chrisohaver Thanks for your reply~


> About the CoreDNS version
In the real environment, local dns and coredns are deployed. and all of them are crashed probabilistic. They all crashed occasionally. 

And the stack(golang)  informations seen on  coredns reboot is the same as above.   same root cause:  `panic: too many concurrent operations on a single file or socket (max 1048575)`

I did some troubleshooting, and the reason is that istio has a lot of serviceEntry configured, and there are a lot of sidecars under the cluster, which regularly and concurrently launch some dns queries for external domains every 30s.

The DNS Query Path:

Sidecars (many)  -> Node Local DNS (go.mod used the v1.7 CoreDNS) -> CoreDNS (1.9) -> Upstream DNS Server

It appears that Node Local DNS / CoreDNS has accumulated many DNS requests, all of which are waiting for responses from the upstream.

**Comment by chrisohaver** [comment]
You can set max concurrent in forward in your configuration to mitigate your issue. But I don’t agree that it’s good to make it the default.

**Comment by zengyuxing007** [comment]
> You can set max concurrent in forward in your configuration to mitigate your issue. But I don’t agree that it’s good to make it the default.

My idea is that we can set the `max_concurret` default value to 1048575 -1. That maybe won't trigger the underlying restriction in the Go language, and  it would not cause CoreDNS process to panic and the  pod to restart.

**Comment by chrisohaver** [comment]
It would have no effect on dns responses not flowing through the forward plugin.

**Comment by chrisohaver** [comment]
I think this would need to be fixed in miekg/dns if it hasn’t already been fixed in the many years since coredns 1.7 was released.

**Comment by chrisohaver** [comment]
@zengyuxing007, can you replicate this error using the latest coredns release?

**Comment by zengyuxing007** [comment]
> @zengyuxing007, can you replicate this error using the latest coredns release?

@chrisohaver  I tried to reproduce it and didn't, there might be some harsh conditions

**Comment by 5HT2** [comment]
> @zengyuxing007, can you replicate this error using the latest coredns release?

Hi, I am still experiencing this on v1.11.3.

For what it's worth, coredns was ran at 19:58:11[^1], and exited with a panic at 05:37:46[^1], but it seems to start DNS non-responses much earlier than that.

I don't think that this happens when I have caching turned off. I will turn logging back on and try to replicate this under the same conditions as before, as I had logging turned off when I first ran into this (earlier today).

```caddyfile
apricot.lan {
    #log
    whoami
    forward . 127.0.0.1
}

. {
    #log
    whoami
    cache
    forward . tls://1.1.1.1 {
        force_tcp
        prefer_udp
        tls_servername cloudflare-dns.com
    }
}
```

```
$ ./coredns
.:53
apricot.lan.:53
CoreDNS-1.11.3
darwin/arm64, go1.21.11, a6338e9
[ERROR] Recovered from panic in server: "dns://:53" too many concurrent operations on a single file or socket (max 1048575)
[ERROR] Recovered from panic in server: "dns://:53" too many concurrent operations on a single file or socket (max 1048575)
[ERROR] Recovered from panic in server: "dns://:53" too many concurrent operations on a single file or socket (max 1048575)
[ERROR] Recovered from panic in server: "dns://:53" too many concurrent operations on a single file or socket (max 1048575)
panic: too many concurrent operations on a single file or socket (max 1048575) [recovered]
	panic: too many concurrent operations on a single file or socket (max 1048575)

goroutine 2044556 [running]:
internal/poll.(*fdMutex).rwlock(0x140000a8380, 0x78?)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.11.linux-amd64/src/internal/poll/fd_mutex.go:147 +0x128
internal/poll.(*FD).writeLock(...)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.11.linux-amd64/src/internal/poll/fd_mutex.go:239
internal/poll.(*FD).WriteMsg(0x140000a8380, {0x1423fa3cac0, 0x1d, 0x1e}, {0x1423b1efd58, 0x18, 0x18}, {0x104d16608, 0x1423f217200})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.11.linux-amd64/src/internal/poll/fd_unix.go:515 +0x60
net.(*netFD).writeMsg(0x140000a8380, {0x1423fa3cac0?, 0x18?, 0x104858ce0?}, {0x1423b1efd58?, 0x1423b1efd64?, 0x14272b07208?}, {0x104d16608?, 0x1423f217200?})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.11.linux-amd64/src/net/fd_posix.go:120 +0x34
net.(*UDPConn).writeMsg(0x140001302a0, {0x1423fa3cac0, 0x1d, 0x1e}, {0x1423b1efd58, 0x18, 0x18}, 0x20?)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.11.linux-amd64/src/net/udpsock_posix.go:176 +0xc8
net.(*UDPConn).WriteMsgUDP(0x140001302a0, {0x1423fa3cac0?, 0x1?, 0x14124ce2ae0?}, {0x1423b1efd58?, 0x0?, 0x0?}, 0x141fdff2510)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.11.linux-amd64/src/net/udpsock.go:262 +0x34
github.com/miekg/dns.WriteToSessionUDP(0x1423f230870?, {0x1423fa3cac0, 0x1d, 0x1e}, 0x1423ba35600)
	/home/runner/go/pkg/mod/github.com/miekg/dns@v1.1.59/udp.go:53 +0x70
github.com/miekg/dns.(*response).Write(0x1423f230870?, {0x1423fa3cac0?, 0x14272b07348?, 0x102b9b9f8?})
	/home/runner/go/pkg/mod/github.com/miekg/dns@v1.1.59/server.go:760 +0x4c
github.com/miekg/dns.(*response).WriteMsg(0x1423adbbc80, 0x1423f230870?)
	/home/runner/go/pkg/mod/github.com/miekg/dns@v1.1.59/server.go:747 +0x94
github.com/coredns/coredns/request.(*ScrubWriter).WriteMsg(0x1423f1b9da0, 0x104d402b0?)
	/home/runner/work/coredns/coredns/request/writer.go:20 +0x80
github.com/coredns/coredns/core/dnsserver.errorAndMetricsFunc({0x1400000f480, 0x9}, {0x104d402b0, 0x1423f1b9da0}, 0x1423b7df290, 0x2)
	/home/runner/work/coredns/coredns/core/dnsserver/server.go:429 +0x1dc
github.com/coredns/coredns/core/dnsserver.(*Server).ServeDNS.func1()
	/home/runner/work/coredns/coredns/core/dnsserver/server.go:271 +0x190
panic({0x1048589a0?, 0x104d13ba0?})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.11.linux-amd64/src/runtime/panic.go:914 +0x218
internal/poll.(*fdMutex).rwlock(0x140000a8380, 0x78?)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.11.linux-amd64/src/internal/poll/fd_mutex.go:147 +0x128
internal/poll.(*FD).writeLock(...)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.11.linux-amd64/src/internal/poll/fd_mutex.go:239
internal/poll.(*FD).WriteMsg(0x140000a8380, {0x1423fa3caa0, 0x1d, 0x1e}, {0x1423b1efd40, 0x18, 0x18}, {0x104d16608, 0x1423f2171c0})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.11.linux-amd64/src/internal/poll/fd_unix.go:515 +0x60
net.(*netFD).writeMsg(0x140000a8380, {0x1423fa3caa0?, 0x18?, 0x104858ce0?}, {0x1423b1efd40?, 0x1423b1efd4c?, 0x14272b07988?}, {0x104d16608?, 0x1423f2171c0?})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.11.linux-amd64/src/net/fd_posix.go:120 +0x34
net.(*UDPConn).writeMsg(0x140001302a0, {0x1423fa3caa0, 0x1d, 0x1e}, {0x1423b1efd40, 0x18, 0x18}, 0x20?)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.11.linux-amd64/src/net/udpsock_posix.go:176 +0xc8
net.(*UDPConn).WriteMsgUDP(0x140001302a0, {0x1423fa3caa0?, 0x1?, 0x14124ce2a50?}, {0x1423b1efd40?, 0x0?, 0x0?}, 0x141fdff2510)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.11.linux-amd64/src/net/udpsock.go:262 +0x34
github.com/miekg/dns.WriteToSessionUDP(0x1423f2307e0?, {0x1423fa3caa0, 0x1d, 0x1e}, 0x1423ba35600)
	/home/runner/go/pkg/mod/github.com/miekg/dns@v1.1.59/udp.go:53 +0x70
github.com/miekg/dns.(*response).Write(0x1423f2307e0?, {0x1423fa3caa0?, 0x14272b07ac8?, 0x102b9b9f8?})
	/home/runner/go/pkg/mod/github.com/miekg/dns@v1.1.59/server.go:760 +0x4c
github.com/miekg/dns.(*response).WriteMsg(0x1423adbbc80, 0x1423f2307e0?)
	/home/runner/go/pkg/mod/github.com/miekg/dns@v1.1.59/server.go:747 +0x94
github.com/coredns/coredns/request.(*ScrubWriter).WriteMsg(0x1423f1b9da0, 0x1423f2307e0?)
	/home/runner/work/coredns/coredns/request/writer.go:20 +0x80
github.com/coredns/coredns/core/dnsserver.errorFunc({0x1400020f000?, 0x104d379e0?}, {0x104d402b0, 0x1423f1b9da0}, 0x1423b7df290, 0x2)
	/home/runner/work/coredns/coredns/core/dnsserver/server.go:417 +0x154
github.com/coredns/coredns/core/dnsserver.(*Server).ServeDNS(0x140000a8280, {0x104d379e0, 0x141fde865a0}, {0x104d402b0, 0x1423f1b9da0}, 0x1423b7df290)
	/home/runner/work/coredns/coredns/core/dnsserver/server.go:318 +0x988
github.com/coredns/coredns/core/dnsserver.(*Server).ServePacket.func1({0x104d41858, 0x1423adbbc80}, 0x1423f1b9d88?)
	/home/runner/work/coredns/coredns/core/dnsserver/server.go:178 +0x94
github.com/miekg/dns.HandlerFunc.ServeDNS(0x14058433200?, {0x104d41858?, 0x1423adbbc80?}, 0x14058433200?)
	/home/runner/go/pkg/mod/github.com/miekg/dns@v1.1.59/server.go:37 +0x38
github.com/miekg/dns.(*Server).serveDNS(0x140006cc000, {0x14058433200, 0x1d, 0x200}, 0x1423adbbc80)
	/home/runner/go/pkg/mod/github.com/miekg/dns@v1.1.59/server.go:663 +0x370
github.com/miekg/dns.(*Server).serveUDPPacket(0x140006cc000, 0x0?, {0x14058433200, 0x1d, 0x200}, {0x104d3de90?, 0x140001302a0}, 0x1423ba35600, {0x0?, 0x0})
	/home/runner/go/pkg/mod/github.com/miekg/dns@v1.1.59/server.go:607 +0x1b4
created by github.com/miekg/dns.(*Server).serveUDP in goroutine 80
	/home/runner/go/pkg/mod/github.com/miekg/dns@v1.1.59/server.go:537 +0x3a0
```

[^1]: My terminal emulator has support for timestamps on command output, which is how come I have specific timestamps to provide, despite having logging turned off, in order to show how this might be annoying to reproduce.

**Comment by johnbelamaric** [comment]
So, maybe we need to finish the work in https://github.com/coredns/coredns/issues/5595#issuecomment-1480133514 which would theoretically spread the load across multiple sockets and avoid this issue. It would be great to do that gracefully, too, rather than panic.
