### ISSUE TITLE
"context deadline exceeded" in quic_test and "rcode refused" on s390x

### ISSUE THREAD

**Issue by skriesch** [miekg/coredns#6682]
**What happened**:
We are building coredns for openSUSE on multiple architectures. I am receiving on s390x the following error messages:
```
[  631s] --- FAIL: TestQUIC (5.00s)
[  631s]     quic_test.go:37: Expected no error but got: context deadline exceeded
[  631s] --- FAIL: TestQUICProtocolError (5.07s)
[  631s]     quic_test.go:93: Expected no error but got: context deadline exceeded
[  631s] --- FAIL: TestView (0.00s)
[  631s]     --- FAIL: TestView/split-name_two.test.test.test.split-name (0.00s)
[  631s]         view_test.go:160: rcode is "REFUSED", expected "NOERROR"
[  631s]     --- FAIL: TestView/split-name_two.test.split-name (0.00s)
[  631s]         view_test.go:160: rcode is "REFUSED", expected "NOERROR"
[  631s]     --- FAIL: TestView/split-name_default.test.split-name (0.00s)
[  631s]         view_test.go:160: rcode is "REFUSED", expected "NOERROR"
[  631s]     --- FAIL: TestView/metadata_test.metadata (0.00s)
[  631s]         view_test.go:160: rcode is "REFUSED", expected "NOERROR"
```
I believe, that there is an (Big Endian related) addressing issue.

**What you expected to happen**:
The build should succeed without any error message on openSUSE Tumbleweed for s390x.

**How to reproduce it (as minimally and precisely as possible)**:
1) Request a test VM in the [LinuxONE Community Cloud](https://github.com/linuxone-community-cloud/technical-resources/blob/master/faststart/deploy-virtual-server.md) with SLES
2) [Upgrade ](https://en.opensuse.org/ZSystems/Upgrade_SLES_to_openSUSE) SLES to openSUSE Tumbleweed 
3) Build coredns on this system (openSUSE Tumbleweed on s390x)
4) Tests will fail

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: 1.11.1
- Corefile: 
```
 {
    # Bind on a specific IP
    bind 127.0.0.1

    # Forward queries for all zones to a resolver using TLS 
    # forward . tls://1.1.1.1:853 tls://1.0.0.1:853

    # Forward queries for all zones to a resolver using plain ol' DNS
    #forward . dns://8.8.8.8:53

    # Forward queries for all zones to /etc/resolv.conf
    forward . /etc/resolv.conf

    # Errors related to query processing are printed to STDOUT
    errors

    # Log all DNS queries
    #log
    
    # Extra debug information
    # debug

    # Resolve hostsnames specified in /etc/hosts
    hosts {
      fallthrough
    }
}

```
- logs, if applicable: [Build log](https://build.opensuse.org/build/openSUSE:Factory:zSystems/standard/s390x/coredns/_log)
- OS (e.g: `cat /etc/os-release`): openSUSE Tumbleweed
- Others: architecture s390x

**Comment by ggardet** [comment]
Same problem on openSUSE Tumbleweed **aarch64**.
But a local `osc build` works just fine, so likely related to build system/performance.

**Comment by azouhr** [comment]
Let me add here, that some of the errors really vanish with a faster machine. This is on a private OBS instance, and no fails are found until github.com/coredns/coredns/test. As you can see from the build times, this is not a speed issue.

```
[   79s] ok        github.com/coredns/coredns/request          0.075s  
[   91s] Not executing TestPrometheusImports: faillint not found  
[   91s] --- FAIL: TestQUIC (5.00s)  
[   91s]     quic_test.go:37: Expected no error but got: context deadline exceeded  
[   91s] --- FAIL: TestQUICProtocolError (5.00s)  
[   91s]     quic_test.go:93: Expected no error but got: context deadline exceeded  
[   91s] FAIL  
[   91s] FAIL     github.com/coredns/coredns/test    18.657s
[   91s] FAIL
[   91s] error: Bad exit status from /var/tmp/rpm-tmp.B4QouF (%check)
[   91s]
[   91s] RPM build errors:
[   91s]     Bad exit status from /var/tmp/rpm-tmp.B4QouF (%check)
[   91s] ### VM INTERACTION START ###
[   91s] Powering off.'''
```

**Comment by skriesch** [comment]
The problem with failing builds exists continuously with the version 1.12.0.

Now we are receiving some more error information:
```
[ 1670s] panic: test timed out after 10m0s
[ 1670s] 	running tests:
[ 1670s] 		TestTransport (10m0s)
[ 1670s] 
[ 1670s] goroutine 16992 [running]:
[ 1670s] testing.(*M).startAlarm.func1()
[ 1670s] 	/usr/lib64/go/1.24/src/testing/testing.go:2484 +0x46a
[ 1670s] created by time.goFunc
[ 1670s] 	/usr/lib64/go/1.24/src/time/sleep.go:215 +0x42
[ 1670s] 
[ 1670s] goroutine 1 [chan receive, 9 minutes]:
[ 1670s] testing.(*T).Run(0xc0001e0c40, {0xa2265a, 0xd}, 0xa5d318)
[ 1670s] 	/usr/lib64/go/1.24/src/testing/testing.go:1859 +0x504
[ 1670s] testing.runTests.func1(0xc0001e0c40)
[ 1670s] 	/usr/lib64/go/1.24/src/testing/testing.go:2279 +0x62
[ 1670s] testing.tRunner(0xc0001e0c40, 0xc0001fbca0)
[ 1670s] 	/usr/lib64/go/1.24/src/testing/testing.go:1792 +0x132
[ 1670s] testing.runTests(0xc00000f6e0, {0x103d280, 0x7, 0x7}, {0xc1eb877da570870d, 0x8bb7ed27d3, 0x104d5c0})
[ 1670s] 	/usr/lib64/go/1.24/src/testing/testing.go:2277 +0x510
[ 1670s] testing.(*M).Run(0xc000244140)
[ 1670s] 	/usr/lib64/go/1.24/src/testing/testing.go:2142 +0x6fc
[ 1670s] main.main()
[ 1670s] 	_testmain.go:57 +0xd8
[ 1670s] 
[ 1670s] goroutine 51 [sync.WaitGroup.Wait, 9 minutes]:
[ 1670s] sync.runtime_SemacquireWaitGroup(0xc000252518)
[ 1670s] 	/usr/lib64/go/1.24/src/runtime/sema.go:110 +0x44
[ 1670s] sync.(*WaitGroup).Wait(0xc000252510)
[ 1670s] 	/usr/lib64/go/1.24/src/sync/waitgroup.go:118 +0x6a
[ 1670s] github.com/coredns/coredns/plugin/dnstap.TestTransport(0xc0001e1340)
[ 1670s] 	/home/abuild/rpmbuild/BUILD/coredns-1.12.0-build/coredns-1.12.0/plugin/dnstap/io_test.go:70 +0x94
[ 1670s] testing.tRunner(0xc0001e1340, 0xa5d318)
[ 1670s] 	/usr/lib64/go/1.24/src/testing/testing.go:1792 +0x132
[ 1670s] created by testing.(*T).Run in goroutine 1
[ 1670s] 	/usr/lib64/go/1.24/src/testing/testing.go:1851 +0x4e4
[ 1670s] 
[ 1670s] goroutine 56 [select]:
[ 1670s] net.(*sysDialer).dialParallel(0xc000360840, {0xb3bd80, 0xc000362f50}, {0xc000343140, 0x1, 0x1}, {0xc000343150, 0x1, 0x1})
[ 1670s] 	/usr/lib64/go/1.24/src/net/dial.go:628 +0x3de
[ 1670s] net.(*Dialer).DialContext(0xc000074d70, {0xb3bbf8, 0x107d600}, {0xa19858, 0x3}, {0xc000252520, 0xa})
[ 1670s] 	/usr/lib64/go/1.24/src/net/dial.go:578 +0x7e4
[ 1670s] net.(*Dialer).Dial(...)
[ 1670s] 	/usr/lib64/go/1.24/src/net/dial.go:504
[ 1670s] net.DialTimeout({0xa19858, 0x3}, {0xc000252520, 0xa}, 0x989680)
[ 1670s] 	/usr/lib64/go/1.24/src/net/dial.go:486 +0x70
[ 1670s] github.com/coredns/coredns/plugin/dnstap.(*dio).dial(0xc000217380)
[ 1670s] 	/home/abuild/rpmbuild/BUILD/coredns-1.12.0-build/coredns-1.12.0/plugin/dnstap/io.go:71 +0x142
[ 1670s] github.com/coredns/coredns/plugin/dnstap.(*dio).serve(0xc000217380)
[ 1670s] 	/home/abuild/rpmbuild/BUILD/coredns-1.12.0-build/coredns-1.12.0/plugin/dnstap/io.go:139 +0x242
[ 1670s] created by github.com/coredns/coredns/plugin/dnstap.(*dio).connect in goroutine 51
[ 1670s] 	/home/abuild/rpmbuild/BUILD/coredns-1.12.0-build/coredns-1.12.0/plugin/dnstap/io.go:89 +0xae
[ 1670s] 
[ 1670s] goroutine 17029 [runnable]:
[ 1670s] net.(*sysDialer).dialParallel.gowrap2()
[ 1670s] 	/usr/lib64/go/1.24/src/net/dial.go:621
[ 1670s] runtime.goexit({})
[ 1670s] 	/usr/lib64/go/1.24/src/runtime/asm_s390x.s:797 +0x2
[ 1670s] created by net.(*sysDialer).dialParallel in goroutine 56
[ 1670s] 	/usr/lib64/go/1.24/src/net/dial.go:621 +0x278
[ 1670s] FAIL	github.com/coredns/coredns/plugin/dnstap	600.330s
[ 1670s] ?   	github.com/coredns/coredns/plugin/dnstap/msg	[no test files]
[ 1670s] ok  	github.com/coredns/coredns/plugin/erratic	0.260s
[ 1670s] ok  	github.com/coredns/coredns/plugin/errors	0.572s
[ 1670s] ok  	github.com/coredns/coredns/plugin/etcd	0.031s [no tests to run]
[ 1670s] ok  	github.com/coredns/coredns/plugin/etcd/msg	0.084s
[ 1670s] --- FAIL: TestZoneReload (0.21s)
[ 1670s]     reload_test.go:69: Expected 3 RRs, got 5
[ 1670s] FAIL
[ 1670s] FAIL	github.com/coredns/coredns/plugin/file	0.360s
[ 1670s] ?   	github.com/coredns/coredns/plugin/file/rrutil	[no test files]
[ 1670s] ok  	github.com/coredns/coredns/plugin/file/tree	0.090s
[ 1670s] --- FAIL: TestHealthMaxFails (0.17s)
[ 1670s]     health_test.go:203: Expected Proxy fails to be greater than 2, got 1
[ 1670s] FAIL
[ 1670s] FAIL	github.com/coredns/coredns/plugin/forward	16.116s
[ 1670s] ok  	github.com/coredns/coredns/plugin/geoip	0.838s
[ 1670s] ok  	github.com/coredns/coredns/plugin/grpc	0.209s
[ 1670s] ok  	github.com/coredns/coredns/plugin/header	0.274s
[ 1670s] ok  	github.com/coredns/coredns/plugin/health	1.373s
[ 1670s] ok  	github.com/coredns/coredns/plugin/hosts	0.135s
[ 1670s] ok  	github.com/coredns/coredns/plugin/k8s_external	0.340s
[ 1670s] ok  	github.com/coredns/coredns/plugin/kubernetes	0.436s
[ 1670s] ?   	github.com/coredns/coredns/plugin/kubernetes/object	[no test files]
[ 1670s] --- FAIL: TestPeriodicWeightUpdate (0.02s)
[ 1670s]     weighted_test.go:144: Test 0: Expected domain w3.example.org. but not found it
[ 1670s]     weighted_test.go:144: Test 0: Expected domain w1.example.org. but not found it
[ 1670s]     weighted_test.go:144: Test 0: Expected domain w2.example.org. but not found it
[ 1670s]     weighted_test.go:205: Final check domains failed
[ 1670s] FAIL
[ 1670s] Not executing TestPrometheusImports: faillint not found
[ 1670s] --- FAIL: TestQUIC (5.10s)
[ 1670s]     quic_test.go:37: Expected no error but got: timeout: no recent network activity
[ 1670s] --- FAIL: TestQUICProtocolError (5.00s)
[ 1670s]     quic_test.go:93: Expected no error but got: context deadline exceeded
[ 1670s] FAIL
[ 1670s] FAIL	github.com/coredns/coredns/test	41.955s
[ 1670s] FAIL
[ 1671s] error: Bad exit status from /var/tmp/rpm-tmp.ET3DCQ (%check)
```
It seems, that not all required containers can coming up.

**Comment by Vishwanatha-HD** [comment]
The Debian engineers from IBM Z team are looking into this issue.. We will update our findings/fixes on this sooner.. Thanks !!

**Comment by srinivas-pokala** [comment]
@skriesch @ggardet @azouhr it seems that quic-go library does not have support for the big endian machine, Due to this tests are failing, found the root cause  for the failures and same tested on s390x machine.
I have attached diff for the same in the below for reference.
```
diff --git a/sys_conn_helper_linux.go b/sys_conn_helper_linux.go
index eec12719..766a8954 100644
--- a/sys_conn_helper_linux.go
+++ b/sys_conn_helper_linux.go
@@ -7,6 +7,7 @@ import (
        "errors"
        "net/netip"
        "os"
+       "runtime"
        "strconv"
        "syscall"
        "unsafe"
@@ -58,7 +59,13 @@ func parseIPv4PktInfo(body []byte) (ip netip.Addr, ifIndex uint32, ok bool) {
        if len(body) != 12 {
                return netip.Addr{}, 0, false
        }   
-       return netip.AddrFrom4(*(*[4]byte)(body[8:12])), binary.LittleEndian.Uint32(body), true
+       ip = netip.AddrFrom4(*(*[4]byte)(body[8:12]))
+       if runtime.GOARCH == "s390x" { // Big endian machine(ex:s390x)
+               ifIndex = binary.BigEndian.Uint32(body)
+       } else {
+               ifIndex = binary.LittleEndian.Uint32(body)
+       }   
+       return ip, ifIndex, true
 }
 
 // isGSOEnabled tests if the kernel supports GSO.
```

**Comment by azouhr** [comment]
This looks nice. Could you please open a submitrequest against quic-go, because in that case, I would be able to submit a patched coredns package.

**Comment by Zxilly** [comment]
I submitted two patches to quic-go fixing related issues, and I think the problem should be solved now.
